name: Create tag on master branch
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  if_tag:
    name: Check if tag created on master branch
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Tag created on master branch
