name: Push to feature branch
on: 
  push: 
    branches: 
      - 'feature/*'
jobs:
  package:
    name: Create docker image
    runs-on: ubuntu-latest
    outputs:
      docker-image: ${{ steps.meta.outputs.tags }}
      tags: $DOCKER_METADATA_OUTPUT_TAGS
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            IMAGE
          tags: |
            type=sha,prefix=,suffix=
          # flavor: |
          #   latest=true  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: 
      - package
    steps:
      - name: Print tags
        run: |
          echo "${{ needs.package.outputs.docker-image }}"     
          echo "${{ needs.package.outputs.tags }}"