name: Push to feature branch
on: 
  push: 
    branches: 
      - 'feature/*'
jobs:
  create-docker-image:
    name: Create docker image
    runs-on: ubuntu-latest
    outputs:
      docker-image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            IMAGE
          tags: |
            type=sha,prefix=,suffix=
          flavor: |
            latest=true  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: 
      - create-docker-image
    steps:
      - name: Print tags
        run: |
          echo "${{ needs.create-docker-image.outputs.docker-image }}"     
