name: Push to feature branch
on: 
  push: 
    branches: 
      - 'feature/*'
jobs:
  package:
    name: Create docker image
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            IMAGE
          tags: |
            type=sha,prefix=,suffix=
          # flavor: |
          #   latest=true  
      - run: |          
          echo "docker-iamge=$DOCKER_METADATA_OUTPUT_TAGS" >> "$GITHUB_OUTPUT"
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: 
      - package
    steps:
      - name: Print tags
        run: |
          echo "$GITHUB_OUTPUT"     