name: Push to feature branch
on: 
  push: 
    branches: 
      - 'feature/*'
jobs:
  package:
    name: Create docker image
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            IMAGE
          tags: |
            type=sha
          flavor: |
            latest=true  
      - run: |
          echo "$DOCKER_METADATA_OUTPUT_TAGS"     
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: 
      - package
    steps:
      - name: Print tags
        run: |
          echo "$DOCKER_METADATA_OUTPUT_TAGS"     