# Push to master branch 
name: Push to master branch
on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'feature/*'
jobs:
  build:
    name: Build with node version ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18, 20 ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: mkdir staging && cp -a build/. staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging 
  create-docker-image:
    name: Create docker image and push to Docker Hub
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Package
        